### ISSUE TITLE
MONITOR Command issue

### ISSUE THREAD

**Issue by Venubabu-Kota** [IBM-Cloud/redli#35]
Hi Team,

In the article, Mentioned like MONITOR command will not be supported by redli but we could see MONITOR as a valid command as per below the provided json. Can anyone please help me the way where I can monitor the redis DB using redli 
client? or any other client tools who can help us to support the MONITOR command

https://github.com/IBM-Cloud/redli/blob/master/commands.json

Thanks in advance.

**Comment by dprosper** [comment]
@ullumullu is this expected to be fixed? I get a series of errors while running monitor, I downloaded the lastes redli, 

```
> monitor
panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12e406a]

goroutine 1 [running]:
main.catchMonitorCmd(0xc0001ed010, 0x7)
        /Users/sterbling/Development/git/icd/repositories/redli/redli.go:332 +0x7a
main.main()
        /Users/sterbling/Development/git/icd/repositories/redli/redli.go:322 +0xf73
```
